services:
  docker:
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    command: ["--host=tcp://0.0.0.0:2376"]
    volumes:
      - docker-storage:/var/lib/docker
      - jenkins-docker-certs:/certs/client
      - jenkins-home:/var/jenkins_home:ro
    networks: [jenkins]

  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    user: root
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    depends_on: [docker]
    networks: [jenkins]

networks:
  jenkins:

volumes:
  jenkins-home:
  jenkins-docker-certs:
  docker-storage:
